Repository zitadel/zitadel-go, pull requests merged in 2025-08, with the labels that each got.

#500 fix(deps): consolidate duplicate dependabot configurations
  .github/dependabot.yml
Labels: bug, os-contribution

#477 feat: allow configurable post-logout redirect URI
  pkg/authentication/authenticate.go
  pkg/authentication/authenticate_test.go
  pkg/authentication/session.go
Labels: enhancement

#478 feat: add local JWT validation for access tokens
  go.mod
  go.sum
  pkg/authorization/oauth/authorizer.go
  pkg/authorization/oauth/jwt.go
  pkg/authorization/oauth/jwt_test.go
  pkg/authorization/oauth/jwt_testhelper_test.go
  pkg/authorization/oauth/rsa_testkey_test.go
Labels: enhancement

#479 feat(client): allow generic oauth2.TokenSource for authentication
  example/admin/admin.go
  pkg/client/middleware/auth.go
  pkg/client/zitadel/client.go
  pkg/client/zitadel/client_test.go
Labels: enhancement

#504 fix(client): thread safety / close method
  pkg/client/client.go
Labels: os-contribution
